"""Create thresholds and alerts tables.

Revision ID: d5e7f9a1b3c5
Revises: c4d6e8f0a2b4
Create Date: 2026-06-13

Schema:
    thresholds  — one row per device, all sensor min/max limits nullable
    alerts      — generated by rules engine on threshold violations
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "d5e7f9a1b3c5"
down_revision: Union[str, None] = "c4d6e8f0a2b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SENSOR_FIELDS = [
    "soil_humidity",
    "temperature",
    "air_humidity",
    "pressure",
    "altitude",
    "light_lux",
    "water_level",
]


def upgrade() -> None:
    # ── thresholds ────────────────────────────────────────────────────────────
    sensor_cols = []
    for field in _SENSOR_FIELDS:
        sensor_cols.append(sa.Column(f"{field}_min", sa.Float(), nullable=True))
        sensor_cols.append(sa.Column(f"{field}_max", sa.Float(), nullable=True))

    op.create_table(
        "thresholds",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("device_id", sa.Integer(), nullable=False),
        *sensor_cols,
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_thresholds_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thresholds")),
        sa.UniqueConstraint("device_id", name="uq_thresholds_device_id"),
    )
    op.create_index(op.f("ix_thresholds_device_id"), "thresholds", ["device_id"])

    # ── alerts ────────────────────────────────────────────────────────────────
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("reading_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("threshold_min", sa.Float(), nullable=True),
        sa.Column("threshold_max", sa.Float(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="alertseverity"),
            nullable=False,
        ),
        sa.Column("resuelta", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_alerts_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["readings.id"],
            name=op.f("fk_alerts_reading_id_readings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_device_id"), "alerts", ["device_id"])


def downgrade() -> None:
    op.drop_index(op.f("ix_alerts_device_id"), table_name="alerts")
    op.drop_table("alerts")
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS alertseverity")

    op.drop_index(op.f("ix_thresholds_device_id"), table_name="thresholds")
    op.drop_table("thresholds")
